external-services:
  google-maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

initial_admin_account:
  username: admin
  password: ${initial_admin_password}


logging:
  path: logs
  level:
    root: INFO
    ac.uk.bristol.cs.santa.grotto: DEBUG
    org.springframework.web: DEBUG

spring:
  #  set env variable SPRING_PROFILES_ACTIVE=dev on dev machine
  profiles.active: prod

  thymeleaf:
    cache: false
